language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: xSIYhhwtzd+DV5oHEiT3ZVVCKsVlabQ7DMjx6xrq5XZtNBlsLSq6FhHJY37rbfI//6jv2PPZS2OUgNvhmDeiCrWbN6cIXZWkOVHcizfkKLvENLwnqvY+RU4gbwRvTfYEs+WPsl7iRRIahjKHGJHNuSnPSOwQ68eMr60WCSvakRX3ZOA0NgDW6v+MwUL9oTK25ArPhd0D98q5PVuvHmPTK/nc/CHjAJKIhrxqtgMb2PXYwX1YgEnHxbVarbVUqJsJ1Wi0t5PWvf6nLGPSp97f5mt7E68G+J+i18gGh9d/LWSpz8b1qOkxqB7xZwFOmp2Z0OyCNP0PeXmEKozdXMaEa5oi1eeIbot1VjjWrX9eL8b4JGLCR7cTLwZ1Zw7mZi3vTVSyqe9UEBZgGQAkixC0Y93TBRgstsv5/wDu2M4tIn68vKtCFRBnViJmau5UikYl0EukzzLB+LuJLZ2HgkhngwTxMdNIpXVDNRvMgRXMBfKYUmIneGNEAS2DJHlm6LDkGUpD4nBVJs1JJ07lRv/w9ithypLHgfOIWWtthr3JLuq0jvjJaVT91vxGcrUhLsXYnQbcy2l5yDXOLi+PA9UY0O/51m2t2hNojsZg2Eu0dNSipH7wZgGI7peO5hqAEx4F5IqlWBopSfHVd2M3CpyRp6yMMGbvZam1zE5RSg093F0=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NCBI_SRA_FTP_HOST=ftpHost
  - CEDAR_NCBI_SRA_FTP_USER=ftpUser
  - CEDAR_NCBI_SRA_FTP_PASSWORD=ftpPassword
  - CEDAR_NCBI_SRA_FTP_DIRECTORY=ftpDirectory
  - CEDAR_IMMPORT_SUBMISSION_USER=submissionUser
  - CEDAR_IMMPORT_SUBMISSION_PASSWORD=submissionPassword
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_SUBMISSION_HTTP_PORT=9010
  - CEDAR_SUBMISSION_ADMIN_PORT=9110
  - CEDAR_SUBMISSION_STOP_PORT=9210
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - secure: MtEIkzgnAGvXAsSUI3PR0labEyrwlmbbzaiWRxWQFnuBNFOOQgerqCbwpxHY3jb+ogpthFrxhDOZTVWZuPACjTrfcGV02PO4w92L9OI+W9uzgKOE5rMcyvw9/1FanDj0NPFqCI2yukvvbBAEEO+/+FEvEErB1Bkx49C8KVNK8rSD3cSp8Nkh1c4hSWqnqrHdqZZDTl5uueWt/3eK+4FTxHPY8BfRY3KFCJO/KNB3OA9l4dehVCcnhAItQouuPkpsNV9Tke64X2hCnWcFHdiu9p0k5rC9dGurhgf9oQyWmY51Gjq4VLTke/oIO7IkXnWdKTfUQMgVnDoLvy/hIrH8VlwGzuwfU9nahJaW0Y1YLETOih2RAqcKtcKD1Epsl44gg89QT7rVRv9aio3MjxgDxI20T01jkgBs9nxUrKOhnFw5Ow7G7wM7n5Qozt5E7ty1GKrw0GmTEjEbczqEL5Aeid3DlDQTf7f+sezovZXPjAc23TLsVWXQXHRt8OSMm4DGU28JxnuEXjD/BeUQHgBSdFbkGj0N5L9+84ltPjizWUgH4T0NBRsOb89AErLDAGY8tZ9Wl205TZcyR3YtU+7WI1f2aEmO4hkDU3G0Rv5sDu++U7lfC5pce38IWsRKEKzTUxMzLgUqMslm4OuvTXK+C3SL6j7S7jWj9rtj/xZIhMo=
  - secure: N0+16rmWEwyqIZtk2zTr1nsTUtAYiqu6QuYFoZNrAOPOgUESZJ9/BsiDWE0KZ4lotUIgBxHMHFtAwtVPtRXF9rybbQwk7Fdp0HQsUfor1cQ56iZ9WJetWH17KM3WTmGHzfN9iyVt4xH9BzbDFNaLVuqno60rHhIbBaKz3gv7kU42FSWcmOeYtLxa87RcCWOjy90pwQSn4a66d9rj/YjLUpohNfMZVnFt8VmZ520DxlGZ0JqptYnca4A2wykfZWCUpEHJ/VNa3U6PnOYniDRzwjjBYfW64/s9GfFq0dBpSooU2YreoLCFtAI1MMM67olF3vJkT+B+R1LjCuEuX1gpPJkPnM6ZCaxDMOIt7iQaLQ6r+AqdNynjzK3UcPEn+r6a/oB6uo/LsCsbV56CSzJ2dwtMakUbPlb4/d7vv8Jfj9TqpvR9LIVvW0rw5RcStrdFo6omOFHSdc7s06oiDqkgx47y7MCAUQvpCBd6cqEmCTUc1kmNiZ7TjgKl7RlJr88lnxvs3Nr+AEJ6KQL3MTdFGs3o9VN+mLKgASpZdjZEd7BSa7XzBdUF5wtIBzot3SyCdJtoIsZhqezoC+5lit5o3QRB7XiayJdjojkSt5UVIZrTw2AXWmnVDymxtm92Lif/RszZgfG0CdNhGlqu2tWu7UMuLErY8nqrWqNJo44dsuM=
